### ISSUE TITLE
[feature request] comprehensive history

### ISSUE THREAD

**Issue by atomicthumbs** [cpsdqs/cohost-dl#16]
as the site nears its close, it would be nice to have an option (defaulting to disabled, because it's a big task and most people don't really want this) to download my entire timeline, finish to start, so i can see everything i saw, and go back and find things i missed someday.

**Comment by c-probably-archived20260718** [comment]
I think you can already do this by just pasting all of your follows into the PROJECTS array in the config. I suppose I could automate that by loading all of your follows and then automatically loading all of their posts? The harder part of this is that I would have to consider optimizing The Cohost Archive Global Feed to work with Big Data…

and probably also throwing away all the post pages and only keeping the post data, because those take up way too much space… and then rendering the post pages… in cohost-dl… somehow……

…I think doing this would be a bit of a project on the scale of making an actual website backend, because I don’t see it working decently without at least an sqlite database.

Well, y’know what? I would perhaps also be interested. It wouldn’t be that hard if it doesn’t concern itself with loading faithful cohost pages, and just loads the data. maybe I’ll get started on that after I run some errands

next day edit: well that wasn’t so hard. wip now available. the hard part will now be rendering the data…

**Comment by atomicthumbs** [comment]
thank you for the wip it works very well

**Comment by c-probably-archived20260718** [comment]
34790b4 adds a dashboard, though with no filtering options yet. I think this more or less completes this feature request
