### ISSUE TITLE
clicking on images attached to posts doesn't expand them

### ISSUE THREAD

**Issue by atomicthumbs** [cpsdqs/cohost-dl#3]
but the thumbnails are there just fine. ~~hell you could probably just replace the thumbnails with the full size images since you have them anyway~~ you did that already

**Comment by randomouscrap98** [comment]
I have a feeling this is due to CORS and opening locally. If you host the files through http, it might start working. I'm going to be hosting my own export pretty soon, I'll see if it fixes it. If it's actually that, there's nothing the downloader can do to fix it, since it's just silly browser things.

**Comment by c-probably-archived20260718** [comment]
I’m planning on doing some post-processing to replace the first-party javascript to replicate its behavior, because cohost’s javascript will of course famously blank the whole page in certain error states (“cohost org doesn’t exist anymore” might count as one), which we don’t really want here…

**Comment by c-probably-archived20260718** [comment]
You can now use the ENABLE_JAVASCRIPT option on the latest version for this. As a next step, I’ll try and see if there’s some way to get it to stop flashing when loading the page with Javascript enabled, but, well, it works!
