### ISSUE TITLE
Some resources are expected to be at content root rather than relative to page location

### ISSUE THREAD

**Issue by randomouscrap98** [cpsdqs/cohost-dl#4]
This makes hosting them under a folder or something break. For instance, if I'm trying to host it under a "cohost" path.  Here, the full path is (currently) https://haloopdy.com/cohost/haloopdy/post/7452593-derfisch.html

![image](https://github.com/user-attachments/assets/9e57fcd5-0172-44a0-ab19-06b264e88a0a)

You should be able to just have the path be relative, like `../../static/etc`. I think, anyway... sometimes I forget lol.

**Comment by c-probably-archived20260718** [comment]
This particular issue is now fixed, but webpack chunks are still being loaded from the root (which I can’t do anything about at the moment), so it doesn’t quite work all the way. Right now, this is a good thing, because when javascript *does* actually succeed loading, the page will crash and turn blank very quickly. I think I’ll close this now and note #2 and #3 for the whole javascript issue

**Comment by randomouscrap98** [comment]
Cool. You're doing a great job btw, thank you for this
